// mypages.js
// 2023-3-1


function upCase(string){
    string = String(string)
    return string.charAt(0).toUpperCase() + string.slice(1);
}


exports.genHome = function(lista, data){
    pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>Home</h1>
                </header>

                <div class="w3-container">
                    <ul class="w3-ul w3-border w3-blue-grey">
                    <li> Lista de Pessoas 
                        <a href="http://localhost:7777/pessoas/">
                            Ordem por ID
                        </a> | 
                        <a href="http://localhost:7777/pessoas/asc">
                            Ordem Ascendente
                        </a> | 
                        <a href="http://localhost:7777/pessoas/desc">
                            Ordem Descendente
                    </li>

                    <li><a href="http://localhost:7777/pessoas/sexo"> Distribuição por Sexos </a></li>

                    <li><a href="http://localhost:7777/pessoas/desportos"> Lista de Desportos </a></li>

                    <li> Top de Profissões 
                        <a href="http://localhost:7777/pessoas/profissao=5">
                            Top 5
                        </a> | 
                        <a href="http://localhost:7777/pessoas/profissao=10">
                            Top 10
                        </a> | 
                        <a href="http://localhost:7777/pessoas/profissao=20">
                            Top 20
                        </a> | 
                        <a href="http://localhost:7777/pessoas/profissao=100">
                            Top 100
                        </a> | 
                        <a href="http://localhost:7777/pessoas/profissao=${lista.length}">
                            Todas as profissões
                        </a>
                    </li>
                    </ul>
                </div>

                <footer class="w3-container w3-deep-purple">
                    <h5>Generated by pessoas-server: ${data}</h5>
                </footer>
            </div> 
        </body>
    </html>
    `
    return pagHTML
}


exports.genMainPage = function(lista, data, title){
    lista.sort()

    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>${title} (${lista.length})</h1>
                    <p><a href="http://localhost:7777"> [Voltar à página principal] </a></p>
                </header>

                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Id</th>
                            <th>Nome</th>
                            <th>Idade</th>
                            <th>Sexo</th>
                            <th>Cidade</th>
                        </tr>
    `

    for(let i=0; i<lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7777/pessoas/${lista[i].id}"> 
                            ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>
                            <a href="http://localhost:7777/pessoas/sexo=${lista[i].sexo}"> 
                            ${lista[i].sexo}
                            </a>
                        </td>
                        <td>${lista[i].morada.cidade}</td>
                    </a>
                </tr>
        `
    }
    
                            
    pagHTML += `
                    </table>
                </div>

                <footer class="w3-container w3-deep-purple">
                    <h5>Generated by pessoas-server: ${data} <a href="http://localhost:7777"> [Voltar à página principal] </a></h5>
                </footer>
            </div> 
        </body>
    </html>
    `

    return pagHTML;
}

exports.genPessoaPage = function(pessoa, data){ 
    var pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>${pessoa.nome}</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>${pessoa.nome}</h1>
                    <p><a href="http://localhost:7777"> [Voltar à página principal] </a></p>
                </header>

                <div class="w3-container">
    `

    pagHTML += `
    <ul class="w3-ul w3-border w3-blue-grey">
    `
    // Automatic way of displaying information about the person
    for (var key in pessoa) {
        pagHTML += `
            <li>${upCase(key)}</li>
        `
        var value = pessoa[key];
        if (typeof value == "object"){
            pagHTML += `
                    <ul class="w3-ul w3-border w3-light-grey">
                    `
            for (var keyi in value){
                if(key == "desportos"){
                    pagHTML += `
                    <a href="http://localhost:7777/pessoas/desportos=${value[keyi]}"> 
                    <li> ${upCase(keyi)} : ${upCase(value[keyi])}</li>
                    </a>
                    `
                }
                else{
                    pagHTML += `
                    <li> ${upCase(keyi)} : ${upCase(value[keyi])}</li>
                    `
                }
            }
            pagHTML += `
            </ul>
            `
        }
        else{
            pagHTML += `
                <ul class="w3-ul w3-border w3-light-grey">
                <li> ${upCase(value)}</li>
                </ul>
            `
        }
    }

    pagHTML+= `
        </ul>
    `

    pagHTML += `
                </div>

                <footer class="w3-container w3-deep-purple">
                    <h5>Generated by pessoas-server: ${data} <a href="http://localhost:7777"> [Voltar à página principal] </a></h5>
                </footer>
            </div> 
        </body>
    </html>
    `

    return pagHTML;
}

exports.genProfissaoPage = function(dict, data, title){
    pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>${title}</h1>
                    <p><a href="http://localhost:7777"> [Voltar à página principal] </a></p>
                </header>

                <div class="w3-container">
                <table class="w3-table-all w3-centered">
                        <tr>
                            <th>Lugar</th>
                            <th>Profissão</th>
                            <th>Número de profissionais</th>
                        </tr>
    `

    var i=1
    Object.entries(dict).forEach(([key, value]) => {
        pagHTML += `
        <tr>
            <td>${i}</td>
            <td>${key}</td>
            <td><a href="http://localhost:7777/pessoas/profissao=${key}">${value}</a></td>
        </tr>
        `
        i+=1
    });

    pagHTML += `
                    </table>
                </div>

                <footer class="w3-container w3-deep-purple">
                    <h5>Generated by pessoas-server: ${data} <a href="http://localhost:7777"> [Voltar à página principal] </a></h5>
                </footer>
            </div> 
        </body>
    </html>
    `
    return pagHTML
}

exports.genSexosPage = function(dict, data, title){
    pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>${title}</h1>
                    <p><a href="http://localhost:7777"> [Voltar à página principal] </a></p>
                </header>

                <div class="w3-container">
                <table class="w3-table-all w3-centered">
                        <tr>
                            <th>Sexo</th>
                            <th>Número de pessoas</th>
                        </tr>
    `

    Object.entries(dict).forEach(([key, value]) => {
        pagHTML += `
        <tr>
            <td>${upCase(key)}</td>
            <td><a href="http://localhost:7777/pessoas/sexo=${key}"/>${value}</a></td>
        </tr>
        `
    });

    pagHTML += `
                    </table>
                </div>

                <footer class="w3-container w3-deep-purple">
                    <h5>Generated by pessoas-server: ${data} <a href="http://localhost:7777"> [Voltar à página principal] </a></h5>
                </footer>
            </div> 
        </body>
    </html>
    `
    return pagHTML
}

exports.genDesportosPage = function(dict, data, title){
    pagHTML = `
    <!DOCTYPE html>
    <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>About people...</title>
            <link rel="stylesheet" href="w3.css"/> 
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-deep-purple">
                    <h1>${title}</h1>
                    <p><a href="http://localhost:7777"> [Voltar à página principal] </a></p>
                </header>

                <div class="w3-container">
                <table class="w3-table-all w3-centered">
                        <tr>
                            <th>Desporto</th>
                            <th>Número de pessoas</th>
                        </tr>
    `

    dict = Object.fromEntries(
        Object.entries(dict).sort(([,a], [,b]) => b - a)
    );

    Object.entries(dict).forEach(([key, value]) => {
        pagHTML += `
        <tr>
            <td>${upCase(key)}</td>
            <td><a href="http://localhost:7777/pessoas/desportos=${key}"/>${value}</a></td>
        </tr>
        `
    });

    pagHTML += `
                    </table>
                </div>

                <footer class="w3-container w3-deep-purple">
                    <h5>Generated by pessoas-server: ${data} <a href="http://localhost:7777"> [Voltar à página principal] </a></h5>
                </footer>
            </div> 
        </body>
    </html>
    `
    return pagHTML
}
